import Foundation
import Testing
@testable import Glow

@Suite("Emoji catalogue")
struct HabitEmojiTests {
    @Test("Every emoji's paired symbol is one the app can actually draw")
    func pairedSymbolsExist() {
        // The pairing is hand-written, which is the only honest way to pick a
        // "closest" symbol — and exactly why it needs checking. A name that
        // never existed, or that a future OS drops, would otherwise render as
        // literal text on someone's phone.
        for icon in HabitEmoji.all {
            #expect(HabitSymbol.isSymbol(icon.symbol), "\(icon.emoji) \(icon.name) -> \(icon.symbol) is not a known symbol")
        }
    }

    @Test("No emoji appears twice")
    func noDuplicateEmoji() {
        let all = HabitEmoji.all.map(\.emoji)
        #expect(Set(all).count == all.count)
    }

    @Test("Every entry is searchable by its own name")
    func searchFindsEachByName() {
        for icon in HabitEmoji.all {
            let hits = HabitEmoji.search(icon.name)
            #expect(hits.contains(where: { $0.emoji == icon.emoji }), "searching \"\(icon.name)\" did not find \(icon.emoji)")
        }
    }

    @Test("Search matches keywords and the paired symbol, not just the name")
    func searchMatchesKeywordsAndSymbol() {
        #expect(HabitEmoji.search("hydrate").contains { $0.emoji == "💧" })
        #expect(HabitEmoji.search("figure.run").contains { $0.emoji == "🏃" })
        #expect(HabitEmoji.search("cardio").contains { $0.emoji == "🏃" })
    }

    @Test("A stored emoji resolves to its nearest symbol")
    func nearestSymbolLookup() {
        #expect(HabitEmoji.nearestSymbol(for: "📖") == "book")
        #expect(HabitEmoji.nearestSymbol(for: "🏃") == "figure.run")
        // Anything outside the curated set has no opinion attached to it.
        #expect(HabitEmoji.nearestSymbol(for: "🫥") == nil)
    }

    @Test("Emoji are not mistaken for symbols")
    func emojiAreNotSymbols() {
        // HabitIconView draws anything outside the symbol catalogue as text,
        // which is how emoji habits render at all.
        for icon in HabitEmoji.all {
            #expect(!HabitSymbol.isSymbol(icon.emoji))
        }
    }

    @Test("The set is grouped and reasonably broad")
    func catalogueShape() {
        #expect(HabitEmoji.groups.count >= 6)
        #expect(HabitEmoji.all.count >= 90)
        for group in HabitEmoji.groups {
            #expect(!group.icons.isEmpty, "\(group.title) is empty")
        }
    }
}

@Suite("Full emoji catalogue")
struct EmojiCatalogueTests {
    @Test("Every emoji ships, grouped the way a keyboard groups them")
    func catalogueLoads() {
        // Generated by Tools/make-emoji-catalog.py from Unicode's emoji-test.txt.
        // If the resource goes missing from the bundle the loader returns an
        // empty array rather than crashing, which would silently ship an empty
        // picker — so the count is the thing worth asserting.
        #expect(HabitEmoji.categories.count == 8)
        #expect(HabitEmoji.everyEmoji.count > 1500)

        let titles = HabitEmoji.categories.map(\.title)
        #expect(titles.first == "Smileys & People")
        #expect(titles.contains("Flags"))
        #expect(titles.contains("Objects"))
    }

    @Test("Keyboard order is preserved, not alphabetised")
    func keyboardOrder() {
        // The grid is only familiar if it matches the order people already
        // know, so the generator keeps Unicode's own ordering.
        let smileys = HabitEmoji.categories.first { $0.title == "Smileys & People" }
        let first = smileys?.emoji.first
        #expect(first?.glyph == "😀")
    }

    @Test("Skin-tone and hair variants are left out")
    func noSkinToneVariants() {
        // The keyboard hides these behind a long press; listing all five inline
        // turns the grid into a wall of the same person.
        let modifiers: Set<Character> = ["\u{1F3FB}", "\u{1F3FC}", "\u{1F3FD}", "\u{1F3FE}", "\u{1F3FF}"]
        for entry in HabitEmoji.everyEmoji {
            #expect(!entry.glyph.contains(where: { modifiers.contains($0) }), "\(entry.name) carries a skin tone")
        }
    }

    @Test("Search matches Unicode names across the whole set")
    func searchAcrossEverything() {
        #expect(HabitEmoji.searchAll("rocket").contains { $0.glyph == "🚀" })
        #expect(HabitEmoji.searchAll("green heart").contains { $0.glyph == "💚" })
        #expect(HabitEmoji.searchAll("zzzzz").isEmpty)
    }

    @Test("No duplicate glyphs across categories")
    func noDuplicates() {
        let all = HabitEmoji.everyEmoji.map(\.glyph)
        #expect(Set(all).count == all.count)
    }
}

@Suite("Symbol catalogue")
struct SymbolCatalogueTests {
    @Test("The picker is small enough to browse")
    func browsableIsSmall() {
        // It was 9,403 — mostly chevrons, transport controls and iOS furniture.
        // The point of thinning is that the whole set can be looked through.
        #expect(HabitSymbol.all.count < 500, "\(HabitSymbol.all.count) is back to being a phone book")
        #expect(HabitSymbol.all.count > 150, "\(HabitSymbol.all.count) is too few to find anything in")
    }

    @Test("Validation is much wider than the picker")
    func validationOutlivesThePicker() {
        // The two sets exist separately for exactly this reason: a habit does
        // not stop being a symbol because the picker stopped offering it.
        for name in ["chevron.right", "wifi", "airplayvideo"] {
            #expect(HabitSymbol.isSymbol(name), "\(name) should still validate")
            #expect(!HabitSymbol.all.contains(name), "\(name) should not be browsable")
        }
    }

    @Test("Every seeded and curated icon survives the thinning")
    func storedIconsStillValidate() {
        // The regression this guards: thin the picker, validate against it, and
        // three of the seeded habits start rendering as literal text.
        for template in DefaultHabits.all where !template.isSpacer {
            #expect(HabitSymbol.isSymbol(template.icon), "\(template.icon)")
        }
        for icon in HabitEmoji.all {
            #expect(HabitSymbol.isSymbol(icon.symbol), "\(icon.symbol)")
        }
        #expect(HabitSymbol.isSymbol(HabitSymbol.default))
    }

    @Test("A fill is not offered where its outline is")
    func fillsAreDropped() {
        for name in HabitSymbol.all where name.hasSuffix(".fill") {
            let outline = String(name.dropLast(5))
            #expect(!HabitSymbol.all.contains(outline), "\(name) and \(outline) are both offered")
        }
    }

    @Test("No keycaps in the picker")
    func noKeycaps() {
        // "T-Rex" used to arrive as `t.bubble` and "100" as `100.circle`. A
        // letter on a key is not a picture of anything.
        for name in HabitSymbol.all {
            let head = name.split(separator: ".").first.map(String.init) ?? name
            #expect(head.count > 1, "\(name) is a keycap")
        }
    }

    @Test("Grouped the way an emoji keyboard groups things")
    func emojiCategories() {
        let titles = HabitSymbol.groups.map(\.title)
        #expect(titles.first == "Smileys & People")
        #expect(titles.contains("Objects"))
        #expect(titles.contains("Travel & Places"))
        // Eight categories exist; Flags has no symbols and is simply absent
        // rather than present and empty.
        #expect(HabitSymbol.groups.allSatisfy { !$0.symbols.isEmpty })
    }

    @Test("Every browsable symbol is one the app can draw")
    func browsableSymbolsAreReal() {
        for name in HabitSymbol.all {
            #expect(HabitSymbol.isSymbol(name), "\(name) is offered but does not validate")
        }
    }
}
