import Foundation

/// The SF Symbols a habit can have.
///
/// **Two sets, and the difference matters.** `groups` and `all` are what the
/// picker browses: a few hundred symbols that stand for something an emoji
/// stands for, in the emoji keyboard's own categories. `known` is every symbol
/// the OS ships, and is what decides whether a *stored* icon is drawn as a
/// symbol or as text.
///
/// They have to be separate. Thinning the picker while validating against it
/// would mean any habit whose icon fell out of the browsable set started
/// rendering as the literal string "figure.flexibility" — including three of
/// the seeded ones.
///
/// Generated by `Tools/make-symbol-catalog.py` from the symbol database that
/// ships with macOS. Regenerate it when Xcode updates; nobody hand-maintains
/// seven thousand strings.
///
/// The stored value is a plain string, so nothing had to migrate when this
/// replaced the earlier emoji field: `isSymbol` decides whether a stored icon
/// is drawn as a symbol or as text, and an emoji created before the change
/// keeps working.
enum HabitSymbol {
    static let `default` = "checkmark.circle"

    /// A symbol for a habit nobody has named yet.
    ///
    /// Drawn from the curated habit set rather than from all nine thousand, so
    /// a new habit opens with something plausibly about a life — not
    /// `car.side.rear.tow.hitch`. It is a starting point and one tap from being
    /// changed, which is the whole reason it can afford to be arbitrary.
    static func random() -> String {
        HabitEmoji.all.randomElement()?.symbol ?? `default`
    }

    struct Group: Decodable, Identifiable {
        let key: String
        let title: String
        let icon: String
        let symbols: [String]

        var id: String { key }
    }

    private struct Catalogue: Decodable {
        let groups: [Group]
        /// Human descriptions for every symbol the picker browses.
        let spokenNames: [String: String]
        /// Every supported symbol name, browsable or not.
        let all: [String]
    }

    /// Loaded once, on first use. Cheaper to hold than to decide at runtime
    /// which of the system's symbols exist.
    private static let catalogue: Catalogue? = {
        guard let url = Bundle.main.url(forResource: "SymbolCatalog", withExtension: "json"),
              let data = try? Data(contentsOf: url)
        else { return nil }
        return try? JSONDecoder().decode(Catalogue.self, from: data)
    }()

    /// What the picker browses.
    static let groups: [Group] = {
        guard let decoded = catalogue?.groups, !decoded.isEmpty else {
            // A missing catalogue should not take the app down, and a picker
            // with one entry is still a working picker.
            return [Group(key: "other", title: "Other", icon: "square", symbols: [HabitSymbol.default])]
        }
        return decoded
    }()

    /// Every symbol the OS ships, which is a much longer list than the picker
    /// shows. Only used to decide whether a stored icon is a symbol.
    private static let known: Set<String> = {
        guard let names = catalogue?.all, !names.isEmpty else { return Set(all) }
        return Set(names)
    }()

    /// The symbol paired with each suggested emoji, in the same order.
    ///
    /// The pairing already existed — `HabitEmoji` carries a hand-picked symbol
    /// for each of its curated icons, and it is what `HabitSymbol.random()`
    /// draws from. This is that list, deduplicated: several emoji share a
    /// symbol, because there are four ways to draw a person running and one
    /// `figure.run`.
    ///
    /// These also appear further down in their own categories. A suggestion is
    /// a shortcut, not a claim of exclusivity, and hiding a symbol from Objects
    /// because it is also suggested would make Objects wrong.
    static let suggested: [String] = {
        var seen = Set<String>()
        return HabitEmoji.suggested.compactMap {
            seen.insert($0.symbol).inserted ? $0.symbol : nil
        }
    }()

    /// Every browsable symbol once, suggestions first, then catalogue order.
    static let all: [String] = {
        var seen = Set<String>()
        var result: [String] = []
        for symbol in suggested where seen.insert(symbol).inserted {
            result.append(symbol)
        }
        for group in groups {
            for symbol in group.symbols where seen.insert(symbol).inserted {
                result.append(symbol)
            }
        }
        return result
    }()

    /// Whether a stored icon should be drawn as a symbol or as plain text.
    ///
    /// Checked against every symbol the OS ships, not against the browsable
    /// set — a habit does not stop being a symbol because the picker stopped
    /// offering it. Anything else is text, which covers both emoji habits
    /// created before symbols existed and any name a future OS drops.
    static func isSymbol(_ icon: String) -> Bool {
        known.contains(icon)
    }

    /// A short VoiceOver description for a tile in the curated picker (#525).
    ///
    /// The generator carries these beside the symbols so an Xcode catalogue
    /// refresh cannot add a visible tile without adding its spoken name. The
    /// fallback keeps a damaged or older bundled catalogue usable, but the
    /// committed catalogue and tests cover every offered symbol.
    static func spokenName(for symbol: String) -> String {
        catalogue?.spokenNames[symbol]
            ?? symbol.replacingOccurrences(of: ".", with: " ")
    }

    /// Symbols whose name contains every word of the query.
    ///
    /// Word-wise rather than substring, so "circle heart" finds
    /// `heart.circle` even though those words appear in the other order.
    static func search(_ query: String) -> [String] {
        let terms = query
            .lowercased()
            .split(whereSeparator: { $0 == " " || $0 == "." })
            .map(String.init)
        guard !terms.isEmpty else { return all }
        return all.filter { name in
            terms.allSatisfy { name.contains($0) }
        }
    }
}
