import Foundation

/// The SF Symbols a habit can have: all of them.
///
/// The catalogue is generated by `Tools/make-symbol-catalog.py` from the symbol
/// database that ships with macOS, filtered to the deployment target and
/// grouped by Apple's own categories in Apple's own order. Regenerate it when
/// Xcode updates; nobody hand-maintains nine thousand strings.
///
/// The stored value is a plain string, so nothing had to migrate when this
/// replaced the earlier emoji field: `isSymbol` decides whether a stored icon
/// is drawn as a symbol or as text, and an emoji created before the change
/// keeps working.
enum HabitSymbol {
    static let `default` = "checkmark.circle"

    struct Group: Decodable, Identifiable {
        let key: String
        let title: String
        let icon: String
        let symbols: [String]

        var id: String { key }
    }

    /// Loaded once, on first use. The file is about 240KB of names, which is
    /// cheap to hold and much cheaper than deciding at runtime which of the
    /// system's symbols exist.
    static let groups: [Group] = {
        guard let url = Bundle.main.url(forResource: "SymbolCatalog", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let decoded = try? JSONDecoder().decode([Group].self, from: data)
        else {
            // A missing catalogue should not take the app down, and a picker
            // with one entry is still a working picker.
            return [Group(key: "other", title: "Other", icon: "square", symbols: [HabitSymbol.default])]
        }
        return decoded
    }()

    /// Every symbol once, in catalogue order. Symbols belong to more than one
    /// category, so this is deduplicated.
    static let all: [String] = {
        var seen = Set<String>()
        var result: [String] = []
        for group in groups {
            for symbol in group.symbols where seen.insert(symbol).inserted {
                result.append(symbol)
            }
        }
        return result
    }()

    private static let lookup = Set(all)

    /// Whether a stored icon should be drawn as a symbol or as plain text.
    ///
    /// Anything in the catalogue is a symbol. Anything else is text, which
    /// covers both emoji habits created before symbols and any symbol name a
    /// future OS stops shipping.
    static func isSymbol(_ icon: String) -> Bool {
        lookup.contains(icon)
    }

    /// Symbols whose name contains every word of the query.
    ///
    /// Word-wise rather than substring, so "circle heart" finds
    /// `heart.circle` even though those words appear in the other order.
    static func search(_ query: String) -> [String] {
        let terms = query
            .lowercased()
            .split(whereSeparator: { $0 == " " || $0 == "." })
            .map(String.init)
        guard !terms.isEmpty else { return all }
        return all.filter { name in
            terms.allSatisfy { name.contains($0) }
        }
    }
}
